language: python
sudo: false
python:
  - "3.5"
env:
  - TOXENV=py2.7-django1.7
  - TOXENV=py2.7-django1.8
  - TOXENV=py2.7-django1.9
  - TOXENV=py3.4-django1.7
  - TOXENV=py3.4-django1.8
  - TOXENV=py3.4-django1.9
  - TOXENV=py3.5-django1.8
  - TOXENV=py3.5-django1.9
install:
  - pip install -q --use-mirrors tox
before_script:
  - createdb -E UTF-8 dash -U postgres -O $USER
script:
  - tox -- --settings=test_runner.settings_travis
