language: python
sudo: false

python:
 - 3.4
 - 3.5
 - 3.6

env:
 - DJANGO_VERSION=1.11.15
 - DJANGO_VERSION=2.0.8

install:
 - pip install -q -r requirements/base.txt
 - pip install -q -r requirements/tests.txt
 - pip install -q django==$DJANGO_VERSION
 - pip install coveralls

before_script:
 - createdb -E UTF-8 dash -U postgres -O $USER

script:
 - coverage run manage.py test --settings=test_runner.settings_travis --verbosity=2 --noinput
 - flake8

after_success:
 - coveralls
