language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
install:
  - pip install tox-travis
before_script:
  - createdb -E UTF-8 dash -U postgres -O $USER
script:
  - tox -- --settings=test_runner.settings_travis
